## Experiment
Try to initialise the following array without typing in all the values


![Array Image](./static/image/array_initialisation_experiment.webp)

In [2]:
import numpy as np

In [6]:
a = np.ones( ( 5, 5 ), dtype="uint8" )
a[ 1:4, 1:4 ], a[ 2, 2 ] = 0, 9

print( a )

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
